### ISSUE TITLE
Not working with graphql actual version

### ISSUE THREAD

**Issue by schmetzyannick** [okgrow/merge-graphql-schemas#104]
When i want to install ( npm install --save merge-graphql-schemas ), I am getting the error: 
+-- UNMET PEER DEPENDENCY graphql@0.11.7
`-- merge-graphql-schemas@1.3.0

npm WARN merge-graphql-schemas@1.3.0 requires a peer of graphql@^0.10.3 but none was installed.

**Comment by RichardLitt** [comment]
Thanks for logging, @schmetzyannick. Can you try installing the package, and let us know if it works? 

```
npm install --save graphql@0.11.7
```

**Comment by RichardLitt** [comment]
This may be fixed by #103.

**Comment by cfnelson** [comment]
@schmetzyannick What version of `merge-graphql-schemas` do you have installed?

**Comment by cfnelson** [comment]
Closing for now. This is only warning you to install `graphql`.  This package expects you to have installed `graphql`. PR #103 should resolve the warning by bumping the `graphql` versions.
