### ISSUE TITLE
fileLoader load files using glob matching 

### ISSUE THREAD

**Issue by thebergamo** [okgrow/merge-graphql-schemas#105]
This module is great, but one thing that can be improved is the fileLoader accept glob matching instead of only one directory. :D

**Comment by RichardLitt** [comment]
Thank you for opening the issue and the PR, @thebergamo! We'll check it out shortly.

**Comment by thebergamo** [comment]
Thanks Richard :D

After getting dig into implementations and integrating with my code I figure that it's not so required, but can be a good improvement to not load all file inside directory only the required ones. 

In my case I split my resources into separate folders and place all my graphql files inside that folders.

**Comment by cfnelson** [comment]
@thebergamo Wanted to let you know that [v1.4.0](https://github.com/okgrow/merge-graphql-schemas/blob/master/CHANGELOG.md#140---2017-12-04) has just been published to npm which includes your work for fileLoader to support a glob pattern. 👍  Thanks again for the PR! 💯

**Comment by thebergamo** [comment]
Thank you guys to having this awesome module!
