### ISSUE TITLE
Dynamic import types and resolvers

### ISSUE THREAD

**Issue by elreeda** [okgrow/merge-graphql-schemas#109]
hey, when calling  `fileLoader` with glob pattern it returns 
> Error: ENOENT: no such file or directory, scandir ...

checking [file_loader](https://github.com/okgrow/merge-graphql-schemas/blob/master/src/file_loader.js) exactly on [Line:28](https://github.com/okgrow/merge-graphql-schemas/blob/master/src/file_loader.js#L28) everything seems to be right, but when I install the package from npm and checking the output `index.cjs.js`, is-glob isn't supported there... my question is the package updated on NPM? 
(I'm currently solving this by copying file_loader.js file into my project)

**Comment by cfnelson** [comment]
@elreeda It's unreleased currently as per the [CHANGELOG](https://github.com/okgrow/merge-graphql-schemas/blob/master/CHANGELOG.md#unreleased) we plan to publish this week.

**Comment by cfnelson** [comment]
@elreeda [v1.4.0](https://github.com/okgrow/merge-graphql-schemas/blob/master/CHANGELOG.md#140---2017-12-04) has just been published to npm. Using a glob pattern should now work. 👍  Let us know if it doesn't now work for you on `v1.4.0`.

**Comment by elreeda** [comment]
🎉 thanks, it works now.
