### ISSUE TITLE
Incompatable with latest graphql (0.12.3)

### ISSUE THREAD

**Issue by davidjohnbell** [okgrow/merge-graphql-schemas#116]
Hello, I tried installing this module but I get this error when running it, any ideas?
`var description = buildASTSchema.getDescription(node);
                                     ^

TypeError: buildASTSchema.getDescription is not a function
    at D:\StreamerServer\node_modules\merge-graphql-schemas\dist\index.cjs.js:4262:38`

**Comment by cfnelson** [comment]
@davidjohnbell Duplicate issue, please see https://github.com/okgrow/merge-graphql-schemas/issues/111 for the temp solution until `0.12.4` is released. You need to revert back to an older `graphql` version or use the `npm` branch, details are on the thread in issue 111.

**Comment by pleerock** [comment]
at least two people faced this issue in last two hours 😆
