### ISSUE TITLE
Tip: Resolver naming convention to aid resolvers fileLoader

### ISSUE THREAD

**Issue by jboothe** [okgrow/merge-graphql-schemas#128]
Thanks for adding the feature that ignores `.js` files when using fileLoader in the typeDefs folder. For those that are curious, it also ignores `.ts` files. It's nice to keep typeDef consolidation confined to the `/typeDefs/index.ts` file when using the automated approach. 

For those that want to use the same approach with resolvers, just use the naming convention of your resolvers to include `.resolvers.` in the file name and use:

```js
const resolversArray = fileLoader(path.join(__dirname, "./*.resolvers.ts"));
```
That way the same "low-maintenance" approach can be used on both typeDefs and resolvers and `src` clean of utilities.

```
|____index.ts
|____resolvers
| |____index.ts
| |____simple.resolvers.ts
| |____user.resolvers.ts
|____typeDefs
| |____index.ts
| |____simple.typedefs.graphql
| |____user.typedefs.graphql
```

**Comment by RichardLitt** [comment]
Thanks, @jboothe. This sounds initially to me like a good tip to include in the Readme. Would you like to make a PR to include it, to become a contributor?

**Comment by jboothe** [comment]
Love to. PR coming shortly.

**Comment by jboothe** [comment]
@RichardLitt PR #129 all done. Thanks for the invite.

**Comment by RichardLitt** [comment]
Awesome! One of the other maintainers will take a look at it as soon as they can. Thank you!

**Comment by RodMachado** [comment]
@jamielob Thanks again for the PR!
I've merged it so I believe we can close this issue.
