### ISSUE TITLE
Resolver merging results in empty objects

### ISSUE THREAD

**Issue by artemzakharov** [okgrow/merge-graphql-schemas#131]
When I try to merge my resolvers, it seems like it picks up the object names, but not the functions. For example, I have this mock resolver file, identical to the doc example save for being a `.ts` file since that's how my project is set up:

`testresolvers/productResolver.ts`:
```
export default {
  Query: {
    products: () => {},
    product: () => {},
  },
  Product: {
    client: () => {},
  },
};
```

I generate the merged result as follows:
```
  const resolversArray = fileLoader(path.join(__dirname, './testresolvers'), {
    extensions: ['.ts'],
  });
  const mergedResolvers = mergeResolvers(resolversArray);
```

When I `JSON.stringify()` the `mergedResolvers` object for readability and log it to the console, this is what I get:

`{"Query":{},"Product":{}}`

It's definitely hitting the file since it picks up `Query` and `Product`, but the actual functions are missing. Any idea what might be causing it to drop the `products`, `product`, and `client` functions?

**Comment by artemzakharov** [comment]
Well, this is embarrassing... but I didn't realize that you couldn't straight up log methods like that! I ran the merged object through a SO snippet that logs method names, and lo and behold, there they were. Might be prudent to add a small disclaimer to the docs that highlights this behavior for fools like myself!

**Comment by RichardLitt** [comment]
> Might be prudent to add a small disclaimer to the docs that highlights this behavior for fools like myself!

Since you've been through it and come out the other side, you might be the best person to know what the docs need. What about crafting a small PR? Sound like something you'd like to do? :)
