### ISSUE TITLE
"extend" use for Query and Mutation across separate files

### ISSUE THREAD

**Issue by deklanw** [okgrow/merge-graphql-schemas#139]
Hi,

I have a simple structure that looks like this:

`const typeDefs = mergeTypes(fileLoader(path.join(__dirname, './schemas')));
`
```
# post.graphql
type Post {
  id: String!
  name: String!
}

extend type Query {
   posts: [Post!]
}

extend type Mutation {
  addPost(name: String!): Post!
}
```

```
# user.graphql
type User {
  id: String!
  name: String!
}

extend type Query {
   users: [User!]
}

extend type Mutation {
  addUser(name: String!): User!
}
```

With this setup I get the following error, 

> Error: Specified query type "Query" not found in document.

I realize that if I remove the "extend" keyword here everything works fine. But, I'm trying to maintain compatibility with this VSCode linting/autocomplete plugin: https://github.com/kumarharsh/graphql-for-vscode

If I remove "extend" I get an error about having non-unique types by this plugin. If I include "extend" I get the error I quoted above.

I would like to keep this file structure I have. Is there a way around this error?

Thanks for any help!

**Comment by RodMachado** [comment]
Hi @deklanw,

The `extend` keyword works by extending an existing type. So you need to either create a separate empty `Query` type, and then the types you described above would extend it. Or use `extend` on only one of your type files. That should make it work.

Let me know if that helps.

Cheers!

**Comment by RodMachado** [comment]
BTW @deklanw, if you are using apollo's [graphql-tag](https://github.com/apollographql/graphql-tag), you probably don't need to use this package. 
We will publish an article showing how this can be accomplished soon.

**Comment by Xample** [comment]
@RodMachado any new since ? I am stuck with the same problem as @deklanw

**Comment by RodMachado** [comment]
@Xample Check the comment I made on May 11. This is not an issue and this should've been closed. 

Feel free to reach out if you're still having issues.

Thanks!

**Comment by dohomi** [comment]
@RodMachado you were mentioning an article to show how this could be accomplished by `graphql-tag`. Is that available? Thanks
