### ISSUE TITLE
Handling additional GraphQL types

### ISSUE THREAD

**Issue by marklawlor** [okgrow/merge-graphql-schemas#14]
Is it possible for this library to handle additional GraphQL types such as 

- [Input](http://graphql.org/learn/schema/#input-types)
- [Enumeration](http://graphql.org/learn/schema/#enumeration-types)
- [Scalar](http://graphql.org/learn/schema/#scalar-types)

Currently the `mergeTypes` function strips these types, causing me to manually handle them separately

**Comment by RodMachado** [comment]
Hey @marklawlor,

Version 0.0.9 is now handling `Input`, `Enumeration` and `Scalar` types. 

Let me know if it works for you and if you find other scenarios we might need to handle.

Cheers!
