### ISSUE TITLE
Support of extensions ts/js with globs ?

### ISSUE THREAD

**Issue by appsolutegeek** [okgrow/merge-graphql-schemas#142]
Hi,

I would like the run the fileloader with ts/js files. At runtime after a build, of course, it is JS but I also run ts-node so I would like to use TS files.

I have tried all these but they either return an empty string or completely crash. I think I don't have the syntax down correctly.

First of all, this after a build works, notice the direct js
`    const resolversArray = fileLoader(join(__dirname, './graphql/**/resolvers/**/*.resolver.js'));`

I have tried this
`    const resolversArray = fileLoader(join(__dirname, './graphql/**/resolvers/**/*.resolver.*'), { extensions: ['.js', '.ts'] });`

and this
`    const resolversArray = fileLoader(join(__dirname, './graphql/**/resolvers/**/*.resolver'), { extensions: ['.js', '.ts'] });`

but neither work, am I using it correctly?

Any help really appreciated

Thanks

**Comment by appsolutegeek** [comment]
My bad, after tracing it through via ts-node - I noticed an issue with my path. All is working as it should.

**Comment by RichardLitt** [comment]
Thanks for following up, @appsolutegeek!
