### ISSUE TITLE
Compatibility with Apollo Server v2 gql tag

### ISSUE THREAD

**Issue by alex996** [okgrow/merge-graphql-schemas#149]
From [Migrating to v2.0](https://www.apollographql.com/docs/apollo-server/v2/migration-two-dot.html#gql-tag)

> Apollo Server 2.0 ships with the `gql` tag for **editor syntax highlighting** and **auto-formatting** with Prettier. [It] requires wrapping your schema with `gql`.

Now that `apollo-server` v2 is in rc, is there any plans to make this library compatible with `gql` tag? `mergeTypes` only works on strings, hence to get syntax highlighting, the best we can do is outsource our schema types into `.gql` or `.graphql` files and require them with the requisite webpack loader.

In Apollo v2, we can wrap our schema with `gql` to go from a string to an AST. But of course it can't then be used with `mergeTypes`. As a workaround, I am still combining my schema and resolvers with `makeExecutableSchema` and passing the results to `ApolloServer` under `schema` prop. It plays well with this library as well. But it'd be better if it were made compatible with `gql`. That way we can, among other things, keep our schema in `.js` files.

Thanks

**Comment by cfnelson** [comment]
@alex996 If I am understanding your question correctly you are wanting to store your `graphql` in multiple `js` files. Would you be wishing to use the file loader or just the `mergeTypes`? 
Currently I don't think we have any plans to add support this as the use case for this pkg was to modularise your graphql schema. 

We are always open though to reconsider if this is something that someone wants to work on and champion.

**Comment by alex996** [comment]
@cfnelson You know what, never mind. It seems possible with apollo v2 [out of the box](https://github.com/apollographql/apollo-server/issues/1298). Then for resolvers, it's easier to just pass a plain array. But thanks for your reply nonetheless

**Comment by nadilas** [comment]
> @cfnelson You know what, never mind. It seems possible with apollo v2 [out of the box](https://github.com/apollographql/apollo-server/issues/1298). Then for resolvers, it's easier to just pass a plain array. But thanks for your reply nonetheless

Just to be sure, you solve this by running `gql()` on the return value of `mergeTypes`, correct?
