### ISSUE TITLE
Prisma-Binding cannot extract fragments from fileLoader

### ISSUE THREAD

**Issue by LawJolla** [okgrow/merge-graphql-schemas#153]
Great work everyone!  Thank you so much for your efforts.  

I'm not sure where the problem lies, here, with Prisma, or with me.  And if it's even a problem -- I have a feeling there are slight variations between implementations leading to the following:

Here is my resolver index file:
```
const { extractFragmentReplacements } = require(`prisma-binding`)
const { fileLoader } = require("merge-graphql-schemas")
const path = require("path")

const resolvers = fileLoader(path.join(__dirname, "../entity/**/resolver.js"))
const fragmentReplacements = resolvers
const fragmentReplacements = extractFragmentReplacements(resolvers)
module.exports = { resolvers, fragmentReplacements }
```

Within those resolvers are fragments that look like the following...

```
const Vehicle = {
   Query: { ... },
   Mutation: {...},
   Vehicle: {
      ...
      heroImage: {
        fragment: `fragment HeroImage on Vehicle { id }`,
        resolve: async (parent, source, ctx, info) => {
          const { heroImageLoader } = ctx.loaders
          return heroImageLoader.load({ id: parent.stockNo.toString(), info })
        }
      }
   }
}

module.exports = Vehicle
```

The server boots and runs fine, however, the fragments are not extracted.  When `fileLoader` is removed and resolvers hand written, the fragments are extracted and behave correctly.  See, e.g. https://github.com/prismagraphql/graphql-server-example/blob/master/src/resolvers/index.ts

Any help is extremely appreciated!

**Comment by LawJolla** [comment]
Fixed this one with a little help from loads.merge.  Hope this helps someone else out!

```
...
const mergedResolvers = resolvers.reduce((result, val) => merge({}, result, val), {})
const fragmentReplacements = extractFragmentReplacements(mergedResolvers)
...
```

**Comment by RichardLitt** [comment]
Thanks for logging! Glad you got this working. :)
