### ISSUE TITLE
support for graphql 14.0.0

### ISSUE THREAD

**Issue by polco** [okgrow/merge-graphql-schemas#165]
Would be nice to have graphql@14.0.0 in the peerDependencies. As far as i tried, it's working out of the box :)

**Comment by RichardLitt** [comment]
If the tests all pass, I don't see a reason not to go ahead and do this. Want to make a PR, @polco?

**Comment by polco** [comment]
sure !

**Comment by polco** [comment]
Fixed in https://github.com/okgrow/merge-graphql-schemas/issues/168
