### ISSUE TITLE
Module '"fs"' has no exported member 'Dirent'.

### ISSUE THREAD

**Issue by yoloOnTheBattlefield** [okgrow/merge-graphql-schemas#169]
node_modules/merge-graphql-schemas/typings/index.d.ts:2:10 - error TS2305: Module '"fs"' has no exported member 'Dirent'.
 import { Dirent } from 'fs';

what happened with this guys?

**Comment by koenpunt** [comment]
`fs.Dirent` is only available since node 10, but I don't think that's the minimum requirement of this library, so it should be removed, or somehow being included conditionally.

**Comment by cfnelson** [comment]
Thanks for the PR @koenpunt . @yoloOnTheBattlefield The fix for this should be up now in v1.5.6

**Comment by yoloOnTheBattlefield** [comment]
thanks guys!

**Comment by cfnelson** [comment]
@yoloOnTheBattlefield `v1.5.7` Is now released and is the version you should use thanks again @koenpunt
