### ISSUE TITLE
merge.all for more than two resolvers

### ISSUE THREAD

**Issue by glenarama** [okgrow/merge-graphql-schemas#37]
mergeResolvers uses merge(x,y) which takes 2 objects and merges them. For more than two resolvers this will merge the first two only.

merge.all([x,y,z]) works.

**Comment by ZephD** [comment]
Similarly, merging a single resolver (e.g. work in progress: `mergeResolvers([resolver])`) would be solved by the same thing.

**Comment by RodMachado** [comment]
@ZephD 
Thanks for catching that! Added test scenario and implemented your solution. Bumping to version 0.0.16
