### ISSUE TITLE
Comments not showing up

### ISSUE THREAD

**Issue by batjko** [okgrow/merge-graphql-schemas#44]
Hi,

I am adding a bunch of comments to my partial schemas, which are then merged in by using this library's `mergeTypes()` function.

E.g.:
```
const Device = `
  # A device, yay!
  type Device {
    id: ID

    # When this device was created
    createdAt: String

    # Last time the device was updated
    lastUpdatedAt: String
    ...
}
```

But in GraphiQL, I cannot see any of them:

![image](https://cloud.githubusercontent.com/assets/7287076/26639559/1436b086-461d-11e7-81b3-6b9aa037cda0.png)

Does the library strip comments during merging?

**Comment by RodMachado** [comment]
Hi @batjko,

The package was not taking comments into consideration. I'll let you know when I come up with a solution for issues #44 and #45.

Cheers!

**Comment by RodMachado** [comment]
Comments are now being merged with the schema. Please use version 0.0.19.

**Comment by batjko** [comment]
@RodMachado Thanks for the update.
It now seems to be working for individual fields. But not for the types themselves, yet?
e.g.:

![image](https://user-images.githubusercontent.com/7287076/27274753-8169ab14-54cc-11e7-8150-740cd383773f.png)

![image](https://user-images.githubusercontent.com/7287076/27274736-71465534-54cc-11e7-930b-6412913527f3.png)

**Comment by RodMachado** [comment]
Hey @batjko,
Please try version 0.0.22. This should work, if not please let me know.

Cheers!

**Comment by batjko** [comment]
Yup, works as expected now. Many thanks! :bowing_man:
