### ISSUE TITLE
Reserved words in schema comments cause Syntax error

### ISSUE THREAD

**Issue by batjko** [okgrow/merge-graphql-schemas#45]
Hi,

In addition to my other issue (see #44), when I do add comments to my schemas, those comments seem to crash the schema validation, if they contain reserved words. 

I have seen it only with the word `type` so far, at the top of the string, which presumably gets caught as the first "type" occurrence in some regex:
![image](https://cloud.githubusercontent.com/assets/7287076/26640419/91491a6c-461f-11e7-882d-335342400664.png)

![image](https://cloud.githubusercontent.com/assets/7287076/26640460/afe7b3de-461f-11e7-8d98-8eee1baed9fe.png)

But it works fine as soon as I change the word "type" from that first comment:
![selection_300](https://cloud.githubusercontent.com/assets/7287076/26640516/d8b1093c-461f-11e7-8291-8bf5a8c92426.jpg)

I suspect the library simply doesn't account for comments at the moment?

**Comment by RodMachado** [comment]
Hi @batjko,

Please use version 0.0.19. You should get your comments merged with the schema now.

Let me know you run into any issues.

Cheers!
