### ISSUE TITLE
New release breaks multi line comments

### ISSUE THREAD

**Issue by epicallan** [okgrow/merge-graphql-schemas#51]
Hi, 
I was using version 0.0.17 of this lib with these sort of types and it worked well

```
type ResourceData {
  year: Int
  Value: Int
  # is the breakdown of the category eg Gross disbursements for 
  # the ODA category
  id: String
  # Category can be Official (oda, oof), Commercial, Private
  category: String
  # flow either inflow or outflow
  # this is an optional field may not be queried in final data
  typeName: String
}

```

I updated to 0.0.19 and my build broke, it doesn't support multi-line comments.

**Comment by RodMachado** [comment]
Hey @epicallan 
Thanks for letting us know. I'll take a look ASAP.

Cheers!

**Comment by RodMachado** [comment]
Hey @epicallan,

Version 0.0.22 should work fine now. 
Let me know if you find any other issues.

Cheers!

**Comment by epicallan** [comment]
@RodMachado Worked fine. Thanks
