### ISSUE TITLE
multiple merges

### ISSUE THREAD

**Issue by elosoman** [okgrow/merge-graphql-schemas#63]
Just found your package and have been tooling into my project. My structure
/api/types/uss/index.js
/api/types/rds/index.js
both of these directories hold a set of  type, query and mutations schema and resolvers. I use your merge in each of these groups.

then in /api/typedef.js I use your package to combine the two merges from above and recieve a message during server boot 
```
Error: Must provide only one schema definition.
```
and in fact when looking at the merged output there are 3 schema tags

So my question is how should you deal with this? Or do i just stop using the index.js files and import them all in my typedef.js. 

Any thoughts on fileLoader recursing that folder and swooping up them all.

Thanks
Ben

**Comment by elosoman** [comment]
FYI ... looks like i don't have that problem when using .mergeResolvers in the same fashion. I might think this is due to the deepmerge used here?

**Comment by kamilkisiela** [comment]
Solution #64

**Comment by RodMachado** [comment]
Hey @elosoman,
Thanks to @kamilkisiela using version 1.1.0 you may now split your types into separate subfolders.
[I've updated the documentation.](https://github.com/okgrow/merge-graphql-schemas#merging-nested-types)

Hope it helps!

Cheers! 🍺

**Comment by elosoman** [comment]
Sweet ... thanks for the quick turn around! Looks good.
