### ISSUE TITLE
AWS ELB deploying

### ISSUE THREAD

**Issue by akaNightmare** [okgrow/merge-graphql-schemas#68]
When I am trying to deploy on AWS ELB I see next error.
```
0|bk-app   | Error: Cannot find module 'babel-runtime/core-js/object/values'
0|bk-app   |     at Function.Module._resolveFilename (module.js:469:15)
0|bk-app   |     at Function.Module._load (module.js:417:25)
0|bk-app   |     at Module.require (module.js:497:17)
0|bk-app   |     at require (internal/module.js:20:19)
0|bk-app   |     at Object. (/var/app/current/node_modules/merge-graphql-schemas/dist/merge_types.js:7:15)
0|bk-app   |     at Module._compile (module.js:570:32)
0|bk-app   |     at Object.Module._extensions..js (module.js:579:10)
0|bk-app   |     at Module.load (module.js:487:32)
0|bk-app   |     at tryModuleLoad (module.js:446:12)
0|bk-app   |     at Function.Module._load (module.js:438:3)
0|bk-app   |     at Module.require (module.js:497:17)
0|bk-app   |     at require (internal/module.js:20:19)
0|bk-app   |     at Object. (/var/app/current/node_modules/merge-graphql-schemas/dist/index.js:12:20)
0|bk-app   |     at Module._compile (module.js:570:32)
0|bk-app   |     at Object.Module._extensions..js (module.js:579:10)
0|bk-app   |     at Module.load (module.js:487:32)
0|bk-app   |     at tryModuleLoad (module.js:446:12)
0|bk-app   |     at Function.Module._load (module.js:438:3)
0|bk-app   |     at Module.require (module.js:497:17)
0|bk-app   |     at require (internal/module.js:20:19)
0|bk-app   |     at Object. (/var/app/current/node_modules/merge-graphql-schemas/index.js:1:18)
0|bk-app   |     at Module._compile (module.js:570:32)
From:
```
Why need babel for that? 
PS: merge-graphql-schemas 0.0.17 version works fine

**Comment by cfnelson** [comment]
@akaNightmare What version of `Node` & `merge-graphql-schemas` are you running to cause the above bug?

**Comment by akaNightmare** [comment]
@cfnelson 7.6.0

**Comment by cfnelson** [comment]
@akaNightmare Thanks, what version of `merge-graphql-schemas` are you using?

**Comment by akaNightmare** [comment]
@cfnelson 1.1.0(latest)

**Comment by cfnelson** [comment]
@akaNightmare 1.0.0+ is using babel-preset "latest-node4", previously it was transpiling for node6+. Do you get the same error on version `0.0.22` of the package?

**Comment by akaNightmare** [comment]
@cfnelson let me check

**Comment by tankist** [comment]
Same issue here. Just checked all version since 0.0.17 and found that issue appeared in 0.0.19.

Just compare dist/merge_types.js:

0.0.17:

```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _validate_schema = require('./validate_schema');
```

and 0.0.19:

```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _values = require('babel-runtime/core-js/object/values');

var _values2 = _interopRequireDefault(_values);
```

**Comment by akaNightmare** [comment]
@cfnelson I think something wrong in these commits (https://github.com/okgrow/merge-graphql-schemas/commit/99cb4d83162ee10729d9fd196a5876fe4e41b37d https://github.com/okgrow/merge-graphql-schemas/commit/b63838b6f3be53297bdd28b69e0016b80bc18bfc)

**Comment by cfnelson** [comment]
@akaNightmare @tankist Would you be able to clone, checkout & test against [fix-babel-transform-runtime](https://github.com/okgrow/merge-graphql-schemas/tree/fix-babel-transform-runtime) branch to see if these changes resolve your issue. Will be making a PR with these changes shortly.

**Comment by akaNightmare** [comment]
@cfnelson sure

**Comment by cfnelson** [comment]
@akaNightmare Thanks! I have opened up a PR, which I hope will resolve the issue. Will wait to hear how it goes for you.

**Comment by tankist** [comment]
```
 Error: Cannot find module './dist/index'
     at Function.Module._resolveFilename (module.js:469:15)
     at Function.Module._load (module.js:417:25)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/var/app/current/node_modules/merge-graphql-schemas/index.js:1:18)
     at Module._compile (module.js:570:32)
     at Object.Module._extensions..js (module.js:579:10)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/var/app/current/dist/_shared/graphql.js:4:33)
     at Module._compile (module.js:570:32)
     at Object.Module._extensions..js (module.js:579:10)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/var/app/current/dist/app.js:19:19)
     at Module._compile (module.js:570:32)
```

Just checked - it is really do not compile anything on `npm i` - no dist folder at all

**Comment by cfnelson** [comment]
@tankist Thanks for taking a look!!! how are you currently integrating the branch/code with your app to test? The `/dist` isn't in source control so it will be missing

I have been testing locally by running `npm link` in the cloned repo on the `fix-babel-transform-runtime` branch. Then in my test app I can run `npm link merge-graphql-schemas`.

**Comment by cfnelson** [comment]
@akaNightmare @tankist I added the `/dist` folder to the branch. You should now be able to test by running this in your project. `npm install -S git://github.com/okgrow/merge-graphql-schemas#fix-babel-transform-runtime`. If you do test it, let me know if it works. 😄

**Comment by tankist** [comment]
That's exactly how I did it. I've just added the following to the package.json and run npm up:

`"merge-graphql-schemas": "okgrow/merge-graphql-schemas#fix-babel-transform-runtime",`

**Comment by cfnelson** [comment]
@tankist And you are still getting the same ` Error: Cannot find module './dist/index'` ? After doing a clean install? The branch now includes the `/dist` folder and I am unable to reproduce that error any longer.

**Comment by aarohmankad** [comment]
I'm still getting the issue mentioned in the original post.

Node: v8.1.4
`merge-graphql-schemas`: v1.1.0

**Comment by cfnelson** [comment]
@aarohmankad  Does PR https://github.com/okgrow/merge-graphql-schemas/pull/69 resolve the bug for you?

If you haven't tried, you can `npm install -S git://github.com/okgrow/merge-graphql-schemas#fix-babel-transform-runtime`.  to use the branch directly.

**Comment by aarohmankad** [comment]
@cfnelson It does! However, I would really prefer installing a stable module vs. a Github branch.

**Comment by cfnelson** [comment]
@aarohmankad Will aim to merge this asap (next few hours).

**Comment by RodMachado** [comment]
@aarohmankad and @akaNightmare 
Thank you for your patience. Please use version 1.1.1 and let us know if you run into any issues.

Thanks for the help @cfnelson! 🍺 

Cheers!

**Comment by aarohmankad** [comment]
Looking good for my projects! @RodMachado
