### ISSUE TITLE
Proposal: Ability for File Loader to Load Files Recursively

### ISSUE THREAD

**Issue by ncronquist** [okgrow/merge-graphql-schemas#75]
Hi mgs team!

My team would really like to store our typeDef files as .graphql files and we really like the way the file loader can load all of those files from a directory. We expect our graphql schema to get quite large though so we would like to break up our schema directory into more manageable sub-directories. I thought it would be useful for the file loader to be able to load those files recursively rather than loading multiple directories and merging them together.

I have created a fork, added this feature, and tested it with our current schema. If you're interested in adding this feature, I would definitely be up to create a PR and work through any issues you find with it.

Thanks for the awesome module!

[forked merge-types-recursively branch](https://github.com/ncronquist/merge-graphql-schemas/tree/merge-types-recursively)

**Comment by RichardLitt** [comment]
Thanks @ncronquist! This sounds like a great feature to add. 

Going off of the [comparison](https://github.com/okgrow/merge-graphql-schemas/compare/master...ncronquist:merge-types-recursively), I don't think it should take too much time to open a PR for this change. I would encourage it. 

@RodMachado What do you think?

**Comment by RichardLitt** [comment]
This can be closed now! Thanks, @ncronquist. Awesome work.

**Comment by RodMachado** [comment]
@ncronquist 
Thanks for the PR! You can use version 1.1.2.

Cheers! 🍻

**Comment by ncronquist** [comment]
Awesome, thanks for the quick review and release!
