### ISSUE TITLE
Resolvers not working with `Query: `

### ISSUE THREAD

**Issue by igor-ribeiro** [okgrow/merge-graphql-schemas#79]
My resolver looks like this and it doesn't work:
```js
export default {
  Query: {
    authors: () => {},
  },
}
```

But it works when I set it like this:
```js
export default {
  authors: () => {},
}
```

I'm merging this way: 
```js
const rootValue = mergeResolvers(fileLoader(path.join(__dirname, './src/graphql/resolvers')));
```

Am I doing something wrong?

**Comment by igor-ribeiro** [comment]
These are my types
```graphql
type Author {
  id: ID!
  firstName: String!
  lastName: String!
}

type Query {
  authors: [Author]
  author(id: ID!): Author
}
```

**Comment by RichardLitt** [comment]
Thanks @igor-ribeiro. Sounds like a bug. We'll look into this as soon as we can.

**Comment by RodMachado** [comment]
Hey @igor-ribeiro,

How many resolvers are there in your './src/graphql/resolvers' folder? My initial thought here is that you're trying to use mergeResolvers with a single resolver. 

If that's the case, you should be seeing a deepmerge error, something like `Error: first argument should be an array with at least two elements`.

Is this it? If not, please paste the error you're getting.

Thanks!

**Comment by igor-ribeiro** [comment]
Hi @RodMachado ,

At first I got this error, but now I have more resolvers. I'm not getting any errors, but I get `null` as a result.

For example, I have this resolver: ```author: () => []```. When I set it inside a `Query` property and query ` users { id }` I get `users: null`. Removing the `Query` I get the expected result `users: []`

**Comment by igor-ribeiro** [comment]
I had a `console.log` inside the resolver and I figured out that it's not called when is defined like
```js
{
  Query: {
    authors: () => {
      console.log('authors resolver'); // doesn't work
      return [];
    },
  },
}
```
```js
{
  authors: () => {
    console.log('authors resolver'); // works
    return [];
  },
}
```

**Comment by RodMachado** [comment]
Hey @igor-ribeiro,

I'm still not sure about what is happening. Can you show your server configuration?

**Comment by igor-ribeiro** [comment]
@RodMachado I created a repo for better investigation: https://github.com/igor-ribeiro/graphql-server-example

**Comment by RodMachado** [comment]
Hey @igor-ribeiro,

It turns out that when you use `graphqlHTTP` you don't really need to have separate keys for Query/Mutation/Subscription in your resolvers object. All you need is to pass a function for each API endpoint. That's why what you were trying is correct. 

Our documentation needs to be fixed to warn people about this.

Thanks for catching it!

Cheers!! 🍻

**Comment by RichardLitt** [comment]
> Our documentation needs to be fixed to warn people about this.

@igor-ribeiro Would you like to make a PR and to become a contributor? If not, I can go ahead and do it. :)

**Comment by locohost** [comment]
I have separate type and resolver files for each db model. I'm using the fileloader to load/merge them. I put a throw Error("...") in my resolver, it never hits. Graphiql queries are always null. So this exact thing is happening to me now. What is the solution?

**Comment by locohost** [comment]
Nevermind, I resolved the issue. Was missing "resolvers:" attrib name in the makeSchema...

`    const schema = makeExecutableSchema({ typeDefs: mergedTypes, resolvers: mergedResolvers });`

**Comment by RichardLitt** [comment]
Thanks @locohost!
