### ISSUE TITLE
Support for .gql files (mergeTypes)

### ISSUE THREAD

**Issue by euthiago** [okgrow/merge-graphql-schemas#80]
Thank you for this super useful module.

Let me suggest a single line change to add support for .gql files when mergin types:

src/file_loader.js line 40
```
      case '.gql':
      case '.graphqls':
```

Since everything is pretty new when it comes to GraphQL, I have no idea if ".gqls" extension would also be used, but ".gql" is already pretty common!

Once again, thank you!

**Comment by RodMachado** [comment]
Hey @euthiago,

I've added `gql` extension to the `fileLoader` as you've suggested. PR #81. I'll let you know when it's published.

Cheers!

**Comment by euthiago** [comment]
@RodMachado 

I appreciate!

(Vlw Rodrigo! hehe)

**Comment by RodMachado** [comment]
@euthiago 
Your changes were deployed!

Cheers!
