### ISSUE TITLE
FileLoader seems not to work in Meteor

### ISSUE THREAD

**Issue by benjhoo** [okgrow/merge-graphql-schemas#97]
When I use the fileLoader() function in my project, Meteor crash with this issue : 
> Error: ENOENT: no such file or directory, scandir '/imports/api/graphql/types/'

My code is pretty simple :
```
import path from 'path';
import { fileLoader, mergeTypes } from 'merge-graphql-schemas';

const types = fileLoader(path.join(__dirname, './'));

export default mergeTypes(types);
```

The _/imports/api/graphql/types/_ folder really exists and contains 2 JS files with graphql Type (I also tried with .graphql files).

If I import manually my 2 files, the project runs well : 
```
import { mergeTypes } from 'merge-graphql-schemas';
import authorType from './authorType';
import postType from './postType';

const types = [authorType, postType];

export default mergeTypes(types);
```

Any ideas ?
Thanks.

**Comment by cfnelson** [comment]
@benjhoo Where is the fileLoader file located? `__dirname` will give you the current directory of where it's been executed from. 

I believe you just need to fix the path that you are passing to the `fileLoader`. e.g lets assume your code snippet is located in `/imports/startup/server` then `path.join(__dirname, './')` would output `/imports/startup/server/`. Which I suspect isn't what you want.

**Comment by benjhoo** [comment]
Hi,
Wrong path was indeed the problem.
I though '/' was refering to the meteor project root, not the filesystem one.

Using `path.join(/(.+)\.meteor/.exec(process.cwd())[1], __dirname)` solved my problem.
Thank you.

**Comment by ikeyboard** [comment]
@benjhoo Thanks! you save my day!
